from pathlib import Path
from typing import Any
import chromadb


class VectorIndex:
    """
    Wrapper around ChromaDB for semantic vector indexing and retrieval.
    Only consumes pre-computed embeddings generated by providers.
    """

    def __init__(self, persist_directory: str | Path = "./chroma", collection_name: str = "fumi_index"):
        self.persist_directory = Path(persist_directory)
        self.client = chromadb.PersistentClient(path=str(self.persist_directory))
        self.collection = self.client.get_or_create_collection(name=collection_name)

    def add(
        self,
        ids: list[str],
        documents: list[str],
        metadatas: list[dict[str, Any]],
        embeddings: list[list[float]],
    ):
        """
        Add chunks with pre-computed embeddings to the Chroma collection.
        """
        self.collection.add(
            ids=ids,
            documents=documents,
            metadatas=metadatas,
            embeddings=embeddings,
        )

    def delete(self, ids: list[str] | None = None, where: dict[str, Any] | None = None):
        """
        Delete chunks from the Chroma collection by IDs or metadata filter.
        """
        if ids is not None:
            self.collection.delete(ids=ids)
        elif where is not None:
            self.collection.delete(where=where)

    def search(
        self,
        query_embeddings: list[list[float]],
        n_results: int = 5,
        where: dict[str, Any] | None = None,
    ) -> list[dict[str, Any]]:
        """
        Query the Chroma collection using pre-computed embeddings.
        Returns a formatted list of matched chunk search results.
        """
        results = self.collection.query(
            query_embeddings=query_embeddings,
            n_results=n_results,
            where=where,
        )

        formatted = []
        if not results or not results.get("ids") or len(results["ids"]) == 0:
            return formatted

        ids = results["ids"][0]
        documents = results["documents"][0] if results.get("documents") else [None] * len(ids)
        metadatas = results["metadatas"][0] if results.get("metadatas") else [{}] * len(ids)
        distances = results["distances"][0] if results.get("distances") else [0.0] * len(ids)

        for i in range(len(ids)):
            formatted.append({
                "id": ids[i],
                "text": documents[i],
                "metadata": metadatas[i],
                "distance": distances[i],
            })

        return formatted
